### ISSUE TITLE
LaTex rendering is broken

### ISSUE THREAD

**Issue by katilp** [cms-opendata-workshop/workshop2021-lesson-analysisflow#1]
The LaTex rendering (using a href="https://www.codecogs.com/eqnedit.php?latex=4.412") e.g. in 
https://cms-opendata-workshop.github.io/workshop2021-lesson-analysisflow/03-demo-intro/index.html
is broken

**Comment by caredg** [comment]
I can't reproduce that.  I tried with Chrome, Firefox and Safari and the rendering is ok.  I also tried with a CERN proxy with Firefox and it also renders ok.  Could there be something more specific that is triggering this problem?

**Comment by katilp** [comment]
You're right. It was just temporary, now working again for me as well.
